### ISSUE TITLE
`tests-extra-net48` job fails because testing framework gets stuck when processing coverage results

### ISSUE THREAD

**Issue by neon-sunset** [neon-sunset/fast-cache#10]
It appears that `tests-extra-net48` executed with `dotnet test .\tests\FastCache.CachedTests -c release -f net48` gets stuck at the very last step of test suite execution.

The behavior looks like an infinite retry loop that causes memory consumed by the test process to grow until the system runs out of it. Upon sending `SIGINT` / Ctrl+C to the console, the execution exists gracefully passing all tests but it's a question what causes it to get stuck.

Error stack trace is:
```
Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Exception: An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.
```

**Comment by neon-sunset** [comment]
Was fixed with https://github.com/neon-sunset/fast-cache/commit/b493e0a73dbf8094e8aa6b6079235938669e8805#diff-4d7dfc73eece76c77dd67af4037a6ea742e66dfd4c29d3c822f437134b5eda90
