### ISSUE TITLE
IndexOutOfRangeException sometimes crash my app

### ISSUE THREAD

**Issue by m0nax3** [neon-sunset/fast-cache#89]
version: 1.8.1
---exception--- 
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at FastCache.Services.CacheManager.<Trim>g__ExecuteTrim|8_0[K,V](UInt32 trimCount, Boolean takeLock)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by neon-sunset** [comment]
Should be fixed by https://github.com/neon-sunset/fast-cache/releases/tag/1.8.2.

If not, please reopen the issue.
